---
- name: OSPF captures from IOS routers
  hosts: IOS
  connection: network_cli

  tasks:
    - name: Collect IOS OSPF commands
      ios_command:
        authorize: yes
        commands:
           - show run | section ospf
           - show ip ospf interface brief
           - show ip ospf neighbor
           - show ip route ospf
      tags: always

      register: IOSPF

    - name: Save IOS precheck output to a file
      copy:
        content=" \n\n ===show run router ospf=== \n\n {{ IOSPF.stdout[0] }} \n\n ===show ip ospf int bri=== \n\n {{ IOSPF.stdout[1] }} \n\n ===show ip ospf nei=== \n\n {{ IOSPF.stdout[2] }} \n\n ===show ip route ospf=== \n\n {{ IOSPF.stdout[3] \n\n }} "
        dest="./{{ inventory_hostname }}-OSPF-Precheck.txt"
      tags: precheck

    - name: Save IOS postcheck output to a file
      copy:
        content=" \n\n ===show run router ospf=== \n\n {{ IOSPF.stdout[0] }} \n\n ===show ip ospf int bri=== \n\n {{ IOSPF.stdout[1] }} \n\n ===show ip ospf nei=== \n\n {{ IOSPF.stdout[2] }} \n\n ===show ip route ospf=== \n\n {{ IOSPF.stdout[3] \n\n }} "
        dest="./{{ inventory_hostname }}-OSPF-Postcheck.txt"
      tags: postcheck

- name: OSPF captures from XR routers
  hosts: XR
  connection: network_cli

  tasks:
    - name: Collect XR OSPF commands
      iosxr_command:
        commands:
           - show run router ospf
           - show ospf interface brief
           - show ospf neighbor
           - show route ospf
      tags: always

      register: XOSPF

    - name: Save XR precheck output to a file
      copy:
        content=" \n\n ===show run router ospf=== \n\n {{ XOSPF.stdout[0] }} \n\n ===show ospf int bri=== \n\n {{ XOSPF.stdout[1] }} \n\n ===show ospf nei=== \n\n {{ XOSPF.stdout[2] }} \n\n===show route ospf=== \n\n {{ XOSPF.stdout[3] \n\n }} "
        dest="./{{ inventory_hostname }}-OSPF-Precheck.txt"
      tags: precheck

    - name: Save XR postcheck output to a file
      copy:
        content=" \n\n ===show run router ospf=== \n\n {{ XOSPF.stdout[0] }} \n\n ===show ospf int bri=== \n\n {{ XOSPF.stdout[1] }} \n\n ===show ospf nei=== \n\n {{ XOSPF.stdout[2] }} \n\n===show route ospf=== \n\n {{ XOSPF.stdout[3] \n\n }} "
        dest="./{{ inventory_hostname }}-OSPF-Postcheck.txt"
      tags: postcheck

